# User specific aliases and functions
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:/usr/local/nccl_2.3.7-1+cuda9.0_x86_64/lib/:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64/:$LIBRARY_PATH
